"""add_items_tables

Revision ID: 1e779e6de077
Revises: 9030ff12bd4a
Create Date: 2026-05-20 01:20:40.936249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e779e6de077'
down_revision: Union[str, None] = '9030ff12bd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('posted_by_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('lost', 'found', name='itemtype'), nullable=False),
    sa.Column('status', sa.Enum('open', 'found', 'potential_match', 'under_verification', 'under_dispute', 'returned', 'expired', 'archived', 'closed', name='itemstatus'), nullable=False),
    sa.Column('category', sa.Enum('electronics', 'bag', 'id_card', 'keys', 'clothing', 'books_notes', 'wallet', 'jewellery', 'other', name='itemcategory'), nullable=False),
    sa.Column('public_description', sa.Text(), nullable=False),
    sa.Column('private_description', sa.Text(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('location_label', sa.String(length=255), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('date_occurred', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extensions_used', sa.Integer(), nullable=False),
    sa.Column('admin_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['campus_zones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_posted_by_id'), 'items', ['posted_by_id'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_university_id'), 'items', ['university_id'], unique=False)
    op.create_table('item_hidden_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_hidden_questions_item_id'), 'item_hidden_questions', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_hidden_questions_item_id'), table_name='item_hidden_questions')
    op.drop_table('item_hidden_questions')
    op.drop_index(op.f('ix_items_university_id'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_posted_by_id'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
