"""add_trust_events_table

Revision ID: 3a0f3fc4d4f9
Revises: 1e779e6de077
Create Date: 2026-05-20 19:25:29.349892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a0f3fc4d4f9'
down_revision: Union[str, None] = '1e779e6de077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear stale rows from the old schema before restructuring the table
    op.execute("DELETE FROM trust_events")

    # Create the new enum type first (required before ALTER COLUMN can use it)
    op.execute("""
        CREATE TYPE trusteventreason AS ENUM (
            'found_item_posted', 'successful_return',
            'failed_verification_2nd', 'failed_verification_3rd',
            'false_claim_confirmed', 'fraud_confirmed',
            'user_report_received', 'admin_adjustment'
        )
    """)

    # Add new columns
    op.add_column('trust_events', sa.Column('delta', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('trust_events', sa.Column('reference_id', sa.UUID(), nullable=True))
    op.add_column('trust_events', sa.Column('applied_by_id', sa.UUID(), nullable=True))

    # Convert reason column from VARCHAR to the new enum
    op.execute("ALTER TABLE trust_events ALTER COLUMN reason TYPE trusteventreason USING reason::trusteventreason")

    # Remove server default now that table is empty and column exists
    op.alter_column('trust_events', 'delta', server_default=None)

    # Convert created_at to timezone-aware
    op.alter_column('trust_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # Drop old indexes
    op.drop_index('ix_trust_events_created_at', table_name='trust_events')
    op.drop_index('ix_trust_events_id', table_name='trust_events')

    # Add foreign keys for the new columns
    op.create_foreign_key(None, 'trust_events', 'users', ['applied_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trust_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Drop old columns that belong to the previous schema
    op.drop_column('trust_events', 'trust_delta')
    op.drop_column('trust_events', 'note')
    op.drop_column('trust_events', 'fraud_risk_after')
    op.drop_column('trust_events', 'related_entity_id')
    op.drop_column('trust_events', 'fraud_risk_delta')
    op.drop_column('trust_events', 'trust_score_after')

    # ix_trust_events_user_id already exists from the prior schema — no-op


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trust_events', sa.Column('trust_score_after', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trust_events', sa.Column('fraud_risk_delta', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('trust_events', sa.Column('related_entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('trust_events', sa.Column('fraud_risk_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trust_events', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('trust_events', sa.Column('trust_delta', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trust_events', type_='foreignkey')
    op.drop_constraint(None, 'trust_events', type_='foreignkey')
    op.create_index('ix_trust_events_id', 'trust_events', ['id'], unique=False)
    op.create_index('ix_trust_events_created_at', 'trust_events', ['created_at'], unique=False)
    op.alter_column('trust_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('trust_events', 'reason',
               existing_type=sa.Enum('found_item_posted', 'successful_return', 'failed_verification_2nd', 'failed_verification_3rd', 'false_claim_confirmed', 'fraud_confirmed', 'user_report_received', 'admin_adjustment', name='trusteventreason'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('trust_events', 'applied_by_id')
    op.drop_column('trust_events', 'reference_id')
    op.drop_column('trust_events', 'delta')
    # ### end Alembic commands ###
