"""add_verification_and_conversations

Revision ID: 5c46713d9400
Revises: bfa6f47fccda
Create Date: 2026-05-22 23:25:02.914537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c46713d9400'
down_revision: Union[str, None] = 'bfa6f47fccda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('potential_match_id', sa.UUID(), nullable=False),
    sa.Column('lost_item_id', sa.UUID(), nullable=False),
    sa.Column('found_item_id', sa.UUID(), nullable=False),
    sa.Column('lost_owner_id', sa.UUID(), nullable=False),
    sa.Column('found_owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'unlocked', 'paused', 'frozen', name='conversationstatus'), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['found_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['potential_match_id'], ['potential_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('potential_match_id', name='uq_conversation_match')
    )
    op.create_index(op.f('ix_conversations_university_id'), 'conversations', ['university_id'], unique=False)
    op.create_table('verification_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('potential_match_id', sa.UUID(), nullable=False),
    sa.Column('lost_item_id', sa.UUID(), nullable=False),
    sa.Column('found_item_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Enum('path_a', 'path_b', 'path_c', name='verificationpath'), nullable=False),
    sa.Column('ownership_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Enum('approved', 'review', 'rejected', name='verificationresult'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['potential_match_id'], ['potential_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_attempts_found_item_id'), 'verification_attempts', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_lost_item_id'), 'verification_attempts', ['lost_item_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_potential_match_id'), 'verification_attempts', ['potential_match_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_university_id'), 'verification_attempts', ['university_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_user_id'), 'verification_attempts', ['user_id'], unique=False)
    # Extend potentialmatchstatus enum (Section 12.5)
    op.execute("ALTER TYPE potentialmatchstatus ADD VALUE IF NOT EXISTS 'pending_review'")
    op.execute("ALTER TYPE potentialmatchstatus ADD VALUE IF NOT EXISTS 'verified'")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_verification_attempts_user_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_university_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_potential_match_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_lost_item_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_found_item_id'), table_name='verification_attempts')
    op.drop_table('verification_attempts')
    op.drop_index(op.f('ix_conversations_university_id'), table_name='conversations')
    op.drop_table('conversations')
    op.execute('DROP TYPE IF EXISTS verificationpath')
    op.execute('DROP TYPE IF EXISTS verificationresult')
    op.execute('DROP TYPE IF EXISTS conversationstatus')
