"""add_potential_matches_and_notifications

Revision ID: fee117a21c16
Revises: 3a0f3fc4d4f9
Create Date: 2026-05-20 23:04:53.116762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fee117a21c16'
down_revision: Union[str, None] = '3a0f3fc4d4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('lost_item_id', sa.UUID(), nullable=False),
    sa.Column('found_item_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'expired', name='potentialmatchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['found_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lost_item_id', 'found_item_id', name='uq_potential_match_pair')
    )
    op.create_index(op.f('ix_potential_matches_found_item_id'), 'potential_matches', ['found_item_id'], unique=False)
    op.create_index(op.f('ix_potential_matches_lost_item_id'), 'potential_matches', ['lost_item_id'], unique=False)
    op.create_index(op.f('ix_potential_matches_status'), 'potential_matches', ['status'], unique=False)
    op.create_index(op.f('ix_potential_matches_university_id'), 'potential_matches', ['university_id'], unique=False)
    # Replace stale notifications table with Feature G schema
    op.execute("DROP TABLE IF EXISTS notifications CASCADE")
    op.execute("DROP TYPE IF EXISTS notificationtype CASCADE")

    notificationtype = postgresql.ENUM(
        'match_found', 'potential_match_expired', 'verification_passed',
        'verification_failed', 'verification_review', 'claim_received',
        'item_returned', 'post_expiring', 'account_suspended',
        'account_unsuspended', 'general',
        name='notificationtype',
        create_type=True,
    )

    op.create_table(
        'notifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notification_type', notificationtype, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('link', sa.String(length=500), nullable=True),
        sa.Column('reference_id', sa.UUID(), nullable=True),
        sa.Column('read', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.execute("DROP TYPE IF EXISTS notificationtype CASCADE")
    op.drop_index(op.f('ix_potential_matches_university_id'), table_name='potential_matches')
    op.drop_index(op.f('ix_potential_matches_status'), table_name='potential_matches')
    op.drop_index(op.f('ix_potential_matches_lost_item_id'), table_name='potential_matches')
    op.drop_index(op.f('ix_potential_matches_found_item_id'), table_name='potential_matches')
    op.drop_table('potential_matches')
    # ### end Alembic commands ###
